### ISSUE TITLE
Netlify forms submission är tom

### ISSUE THREAD

**Issue by hmazter** [HillsongSweden/julforalla#12]
![Screenshot 2020-11-25 at 21 54 18](https://user-images.githubusercontent.com/805377/100280703-e7621080-2f68-11eb-8123-f9d306b87d74.png)

![Screenshot 2020-11-25 at 21 54 05](https://user-images.githubusercontent.com/805377/100280721-eb8e2e00-2f68-11eb-80d1-e7ec1f5b9283.png)

**Comment by Knogobert** [comment]
Mycket udda, händer det även om man kör en vanlig submit på <form method="POST" ...> ?

**Comment by Knogobert** [comment]
Jo du! Jag kanske vet! 
Tror man behöver rendera formuläret bättre med nuxt, en workaround är att skriva upp det i app.html som nuxt använder som grund/fallback.

Kolla in branchen `feat/netlify-forms` nu och se om det funkar.
