### ISSUE TITLE
GeEnGava.vue drawer component

### ISSUE THREAD

**Issue by Knogobert** [HillsongSweden/julforalla#2]
- [x] Formulär
- [x] Disable submit until validated
- [x] Fix font weirdness
- [x] Swish 123-09 2 21 212
- [x] Form ska ha overflow-hidden
- [x] 50px margins på body
- [x] tillbakaknappen i linje med formuläret
- [x] kolla om man kan låta bli att zooma vid input focus
- [x] Smaller images up top
- [x] Fix animation
- [x] Netlify forms connection
- [x] Add swedish errors `@braid/vue-formulate-i18n`
- [x] If mobile: Send off to Swish after form submit
- [x] If NOT mobile: View QR code & phone number, then await

**Comment by hmazter** [comment]
[Comments from Tobias](https://hillsongsweden.slack.com/archives/G01F448J8MB/p1606160042032100):
> * Skillnad på matkasse och julklapp formulären är att det finns hälsning på matkassen.
> * GDPR boxen dyker upp först när man fyller i sin email adress. Annars är den onödig.
> * “Swisha gåva”-knappen ska vara disabled och grå tills all obligatorisk info är ifylld. Enda obligatoriska info är “val av julklapp och matkasse” samt “summa”. Även GDPR boxen (om man fyllt i email dvs, annars syns den ju inte.)
> * Notera att knappen kommer att gå från enabled till disabled när man fyller i email, eftersom GDPR rutan då dyker upp som är obligatorisk.
> * När man växlar mellan matkasse och julklapp så får de fälten som är samma gärna behålla sina värden. Dvs summa och email. Så om man börjar fylla i summa på julklapp och sedan trycker på matkasse så är summan kvar.
> * Om man skrivit en hälsning, sedan trycker julklapp, och tillbaks igen så får gärna hälsningen finnas kvar.
